#!/usr/bin/env bash

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS testing;
    GRANT ALL PRIVILEGES ON testing.* TO '$MYSQL_USER'@'%';

    CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}_1;
    GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}_1.* TO '$MYSQL_USER'@'%';

    CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}_2;
    GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}_2.* TO '$MYSQL_USER'@'%';
EOSQL
